export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SKIN_ROUTE = '/skin'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
